// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KLCodeNav
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string KLCodeNavString = "9799008b-e5ed-4f7b-84b1-0f200d78c90c";
        public static Guid KLCodeNav = new Guid(KLCodeNavString);

        public const string KLCodeNavCmdSetString = "beca8675-2732-4289-a62b-115c442e79fb";
        public static Guid KLCodeNavCmdSet = new Guid(KLCodeNavCmdSetString);

        public const string guidImagesString = "b0ee82e9-15e0-4ff0-9835-f0029a942483";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeNavMenu = 0x1020;
        public const int CodeNavMenuGroup = 0x1021;
        public const int WpfToolWindowCommandId = 0x0101;
        public const int WinformsToolWindowCommandId = 0x0102;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPic3 = 0x0003;
    }
}